module.exports = {
  User: require("./User.model"),
  AdminSettings: require("./AdminSetting.model"),
  Otp: require("./Otp.model"),
  Role: require("./Role.model"),
  DefaultPermission: require("./DefaultPermission.model"),
  Permission: require("./Permission.model"),
  Ethnicity: require("./Ethnicity.model"),
  MasterTable:require("./MasterTable.model"),
  Dishes:require("./Dishes.model"),
  MyStore:require("./MyStore.model"),
  AboutMe:require("./AboutMe.model"),
  Gallery:require("./Gallery.model"),
  OtherServices:require("./OtherServices.model"),
  FAQ:require("./FAQ.model"),
  Country:require("./Country.model"),
  State:require("./State.model"),
  Grocery:require("./Grocery.model"),
  DistanceUnit:require("./DistanceUnit.model"),
  WishList:require("./WishList.model"),
  FavouriteDish:require("./FavouriteDish.model"),
  Drivers:require("./Drivers.model"),
  Membership:require("./Membership.model"),
  Features:require("./Features.model"),
  Type:require("./Type.model"),
  Feedback:require("./Feedback.model"),
  Availability:require("./Availability.model")
};
