module.exports = {
  User: require("./User.model"),
  AdminSettings: require("./AdminSetting.model"),
  Otp: require("./Otp.model"),
  Role: require("./Role.model"),
  DefaultPermission: require("./DefaultPermission.model"),
  Permission: require("./Permission.model"),
  Ethnicity: require("./Ethnicity.model"),
  MasterTable:require("./MasterTable.model"),
  AddDish:require("./AddDish.model"),
  MyStore:require("./MyStore.model"),
  AboutMe:require("./AboutMe.model"),
  MyPhotos:require("./MyPhotos.model"),
  OtherServices:require("./OtherServices.model"),
  FAQ:require("./FAQ.model"),
  Country:require("./Country.model"),
  State:require("./State.model"),
  Discount:require("./Discount.model"),
  GroceryList:require("./GroceryList.model"),
  DistanceUnit:require("./DistanceUnit.model"),
  WishList:require("./WishList.model"),
  FavouriteDish:require("./FavouriteDish.model"),
};
